### ISSUE TITLE
Jumps to the bottom of the document after correction

### ISSUE THREAD

**Issue by evgkra** [robindijkhof/overleaf-textarea#58] opened 2021-08-16 10:28 UTC
Hello, thank you for the helpful extension! 
I am having a bit of trouble sometimes though, everything jumps to the bottom of the document after a correction. This doesn't happen every time, but quite often.
Best regards

**Comment by robindijkhof** [comment] 2021-08-22 21:05
Any chance you can 100% reproduce this? Also, what browser are you using?

**Comment by evgkra** [comment] 2021-08-23 11:14
Yes! This happens to me quite often, to reload the page can help sometimes but not necessarily. The same goes for a friend of mine, we both use chrome

**Comment by robindijkhof** [comment] 2021-08-23 18:57
But how do I reproduce this?

**Comment by dsdoermann** [comment] 2021-09-02 00:11
Have you been able to reproduce this?  It seems to  be happening to me when I use track changes.  Even after I turn off track changes.  I can exit overleaf completely, restart and it seems fine.  The only other time I seemed to have it is when I turned on textarea in chrome after entering overleaf.

**Comment by dsdoermann** [comment] 2021-09-02 17:22
I THINK I can reproduce this.  Open overleaf with text area.  Turn on Track changes in overleaf (You have to have a paid version).  Then it starts jumping.  I confirmed that it is not opening history, for example.  But it may be that extra panel that gets opened when you click review?

**Comment by robindijkhof** [comment] 2021-09-02 18:13
@dsdoermann, unfortunately, I do not have a paid version. Could you check for me whether it is related to the sync scroll option?

**Comment by dsdoermann** [comment] 2021-09-03 16:34
Ill keep trying to get a very specific case.

**Comment by dsdoermann** [comment] 2021-09-07 02:09
Im seeing another pattern I think....  Try to introduce an error, but close the browser window before Grammarly has a chance to detect it.  Then go back and correct it.  Seems to be pretty consistent.

**Comment by robindijkhof** [comment] 2021-09-18 18:32
This will probably be fixed by the next release. It seems related to the sync scroll feature. The scroll position seems to be incorrectly 0 upon fixing a mistake with Grammarly.

**Closed by robindijkhof** 2021-09-18 18:32 UTC
